labkey: <% if File.exist?(Rails.root.join('.labkey')) %>
          <%= File.open(Rails.root.join('.labkey')).first.chomp %>
        <% else %>
          <%= nil %>
        <% end %>

adminkey: <% if File.exist?(Rails.root.join('.adminkey')) %>
            <%= File.open(Rails.root.join('.adminkey')).first.chomp %>
          <% else %>
            <%= nil %>
          <% end %>